sudo : required
services : 
  - docker

before_install: 
  - docker build -t makad747/docker-test -f Dockerfile.dev .

script:  
  - docker run -e CI=true makad747/docker-test npm run test -- --coverage